spring:
  redis:
    host: 
    password: 
    port: 
    database: 0
  cloud:
    gateway:
      globalcors: # 全局的跨域处理
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*" # 允许哪些网站的跨域请求
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 3600000 # 这次跨域检测的有效期
        add-to-simple-url-handler-mapping: true
      routes: # 网关路由配置
        - id: wkwk-service-user
          uri: lb://wkwk-service-user
          predicates:
            - Path=/wkwk/user/**
        - id: wkwk-service-video
          uri: lb://wkwk-service-video
          predicates:
            - Path=/wkwk/video/**
        - id: wkwk-service-interact
          uri: lb://wkwk-service-interact
          predicates:
            - Path=/wkwk/interact/**
logging:
  level:
    com:
      gtkang:
        wkwkgateway:
          mapper: debug
          service: info
          controller: info