spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wkwkdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 2710
  redis:
    host:
    port:
    password:
    database: 0
  servlet:
    multipart:
        enabled: true
        max-file-size: 255MB
        max-request-size: 1024MB
rocketmq:
  name-server: 1.14.111.29:9876
  producer:
    group: user-service-message
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
# 配置mybatis
mybatis:
  #mapper配置文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #标准输出
logging:
  level:
    com:
      wkwk:
        mapper: debug
        service: info
        controller: info
#配置redisson
redisson:
  address: 'redis://124.221.176.164:6380'